### ISSUE TITLE
 Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by tseemann** [ctSkennerton/minced#12]
I downloaded the 0.2.0 jar and got this error:
```
 Unsupported major.minor version 52.0
```
My default is Java 1.7 so I assume this is the problem?

Can backward compatible JAR files be made?

**Comment by ctSkennerton** [comment]
I've uploaded a new jar file into the release which I hope is properly compiled against java 1.6. Can you test it to make sure it works.

**Comment by tseemann** [comment]
@ctSkennerton I confirm that the new extra JAR works on Java 1.7 and 1.6 - Thank you!
