### ISSUE TITLE
CRISPRDetect: A flexible algorithm to define CRISPR arrays

### ISSUE THREAD

**Issue by tseemann** [ctSkennerton/minced#14]
Just FYI

http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4869251/

CRISPRDetect: A flexible algorithm to define CRISPR arrays

CRISPR (clustered regularly interspaced short palindromic repeats) RNAs provide the specificity for noncoding RNA-guided adaptive immune defence systems in prokaryotes. CRISPR arrays consist of repeat sequences separated by specific spacer sequences. CRISPR arrays have previously been identified in a large proportion of prokaryotic genomes. However, currently available detection algorithms do not utilise recently discovered features regarding CRISPR loci.

**Comment by ctSkennerton** [comment]
I reviewed the paper
