### ISSUE TITLE
java error: Exception in thread "main" java.lang.NoClassDefFoundError: IntervalSearchTree$IntervalNode

### ISSUE THREAD

**Issue by Ruonan0101** [ctSkennerton/minced#17]
Hi, 
I am running the version 0.2.1 made by java 1.8.0. But I just got the error like "Exception in thread "main" java.lang.NoClassDefFoundError: IntervalSearchTree$IntervalNode" ..."Caused by: java.lang.ClassNotFoundException: IntervalSearchTree$IntervalNode". 
There is still output file but I cannot trust the results cause of this error msg. What should I do to fix this? Thanks.

**Comment by ctSkennerton** [comment]
Hi,

Did you use the jar file downloaded from github or compile the files yourself using the makefile?

**Comment by Ruonan0101** [comment]
compile the files yourself using the makefile. There is no jar file when I cloned the repo.

**Comment by Ruonan0101** [comment]
I v tried both. Download the minced.jar from the latest release and module load java 1.8.0 to make the jar. But they gave me the same error msg.

**Comment by ctSkennerton** [comment]
That's very strange cause I'm using Java 1.8 and tried compiling on two different computers, a Mac and Linux, without issue. I just uploaded onto github another jar file compiled for Java 1.6. Could you try that one out.

**Comment by Ruonan0101** [comment]
Thanks for the update. I tried the new jar 1.6. still the same error on my metagenome (12GB). but when I split the file into small ones, it turned out with no error. Guess there are some limits here.

**Comment by ctSkennerton** [comment]
Ah I see. Are you trying to run minced on raw metagenome reads or on assembled contigs? If you're running it on reads I would recommend my other program, [crass](https://github.com/ctskennerton/Crass), which was designed for this. Minced should be used on assembled contigs

**Comment by Ruonan0101** [comment]
oh good to know. I am running metagenome reads and the length limit 100 makes me throw away lots of reads. Sure. I would like to try CRASS.
