### ISSUE TITLE
Part of repeat put on spacer sequence

### ISSUE THREAD

**Issue by Russel88** [ctSkennerton/minced#21]
Hey,

First of all, thank you for a great tool.

I have found that sometimes part of the repeat sequences appears to be added to the spacer sequences. See for example below where all spacers end with GTTGTGGTTTG. This sequence is most likely part of the repeats and not the spacers. Furthermore, in several related genomes the repeats of this array is correctly identified as GTTGTGGTTTGATGTCAATTAAGGATTTAGGATATT (that is, the combination of the ending 11bp of the spacers with the repeats from below).

In all the cases I have seen this problem, the array starts right at the beginning of the contig.

Cheers,
Jakob 

CRISPR 3   Range: 1 - 1541
--
POSITION        REPEAT                          SPACER
--------        -------------------------         ----------------------------------------
1               ATGTCAATTAAGGATTTAGGATATT         CCATGACCTTCTTTGTCAGTTCGGTTATGGTTGTGGTTTG        [ 25, 40 ]
66              ATGTCAATTAAGGATTTAGGATATT         TACACAACAAAATTTATCGCGCATAGCGAAGTTGTGGTTTG       [ 25, 41 ]
132             ATGTCAATTAAGGATTTAGGATATT         TGTATCATTTTGTGGCCGTACAGTTGTTACGTTGTGGTTTG       [ 25, 41 ]
198             ATGTCAATTAAGGATTTAGGATATT         AACATTAAGTATCATATCAAATACCCACACGTTGTGGTTTG       [ 25, 41 ]
264             ATGTCAATTAAGGATTTAGGATATT         TAGCTCAATTTTATAGTCTGGCAGAGGACAGTTGTGGTTTG       [ 25, 41 ]
330             ATGTCAATTAAGGATTTAGGATATT         CCCGTGTTATGGCTTGCGTTTTTAAACTTAGTTGTGGTTTG       [ 25, 41 ]
396             ATGTCAATTAAGGATTTAGGATATT         GAAGCTATGAACCATTAATCTGTAGAGAAGGTTGTGGTTTG       [ 25, 41 ]
462             ATGTCAATTAAGGATTTAGGATATT         AATTCGTTGTCTACTATAGTCTTTAATAAGGTTGTGGTTTG       [ 25, 41 ]
528             ATGTCAATTAAGGATTTAGGATATT         AACAGGTAGTTTTTTGGGTAGCAAGAAAGAGTTGTGGTTTG       [ 25, 41 ]
594             ATGTCAATCAAGGATTTAGGATATT         CCATATAGCTCTTAGGAAAGAGGACTGAATGTTGTGGTTTG       [ 25, 41 ]
660             ATGTCAATTAAGGATTTAGGATATT         GACAACGATGAGAAAGCGGCACTTTGTCAAGTTGTGGTTTG       [ 25, 41 ]
726             ATGTCAATTAAGGATTTAGGATATT         AGAGCAAGCACTCTTTAAGTTCACCTTTCAGTTGTGGTTTG       [ 25, 41 ]
792             ATGTCAATTAAGGATTTAGGATATT         TATTAAAATGTATATCAATAGCTTAAAACAGTTGTGGTTTG       [ 25, 41 ]
858             ATGTCAATTAAGGATTTAGGATATT         CCATTGCCTGGCTGGGAAATATCGGAAATAGTTGTGGTTTG       [ 25, 41 ]
924             ATGTCAATTAAGGATTTAGGATATT         TCGGCAATGTCGTAGCCATCATTTCTTTCTGTTGTGGTTTG       [ 25, 41 ]
990             ATGTCAATTAAGGATTTAGGATATT         AGCCTGATACTTGGATAACCATCTATCATGGTTGTGGTTTG       [ 25, 41 ]
1056            ATGTCAATTAAGGATTTAGGATATT         TTTTTGCGGCATATCTGTGCAAACTGCTCAGTTGTGGTTTG       [ 25, 41 ]
1122            ATGTCAATTAAGGATTTAGGATATT         TTACCACAGCCTTTAATAATTGGGTAAACGTTGTGGTTTG        [ 25, 40 ]
1187            ATGTCAATTAAGGATTTAGGATATT         CAGCAGGCAATTATTGGCGATTATGAATGGGTTGTGGTTTG       [ 25, 41 ]
1253            ATGTCAATTAAGGATTTAGGATATT         TATTAAAATGTATATCAATAGTTTAAAACAGTTGTGGTTTG       [ 25, 41 ]
1319            ATGTCAATTAAGGATTTAGGATATT         AGTACGCATGCGTAACTACCAGATGGACCAGTTGTGGTTTG       [ 25, 41 ]
1385            ATGTCAATTAAGGATTTAGGATATT         GCATTGGATGAAATGCTGGCTTTTCTTGAAGTTGTGGTTTG       [ 25, 41 ]
1451            ATGTCAATTAAGGATTTAGGATATT         TTGATGCCTCCCTGGCTGTGACGTGGGCCCGTTGTGGTTTG       [ 25, 41 ]
1517            ATGTCAATTAAGGATTTAGGATATT
--------        -------------------------         ----------------------------------------
Repeats: 24     Average Length: 25              Average Length: 40

**Comment by Russel88** [comment]
For the sake of reproducibility:

I use version 0.3.1 and I have attached a fasta file with two contigs; one contig with the wrong spacers/repeats (BAD) and a contig with similar repeats as the first contig, but where they are correctly identified (GOOD).

[crispr_test.txt](https://github.com/ctSkennerton/minced/files/2410579/crispr_test.txt)

**Comment by ctSkennerton** [comment]
this should be fixed with the latest version 0.3.2

**Comment by Russel88** [comment]
Thank you. I can confirm that it also fixed the other cases I had.

A minor issue now is that the first spacer is dropped. This might be hard to fix though, as the repeat before the first spacer is incomplete, which created the problem in the first place.
