### ISSUE TITLE
Error processing input file

### ISSUE THREAD

**Issue by johnomics** [ctSkennerton/minced#25]
Hello,

Thanks for writing minced, it's a very useful tool.

I'm getting an error running minced 0.3.2 installed via conda:
```
$ minced minced_test.fasta test
Error processing input file 'minced_test.fasta'. Please, check contents.
```

This test file is one sequence from a larger assembly:
[minced_test.fasta.gz](https://github.com/ctSkennerton/minced/files/2866069/minced_test.fasta.gz)

The larger assembly has 78,439 contigs and we see this message 28 times.

I can't see anything obviously wrong with the FASTA file, and we get what looks like sensible output from minced otherwise.

Please could you see what's causing a problem with this contig?

Many thanks
John

**Comment by ctSkennerton** [comment]
Hi John,

Thanks for reporting this, I can confirm that I get the same bug. Unfortunately I'm super swamped at my day job and don't have time to work on personal projects right now. Sorry I can't provide an immediate fix, I'll get to this as soon as possible.

Cheers,
Connor

**Comment by johnomics** [comment]
Hi Connor - thanks for confirming. Don't worry, I know how it is. We'll proceed with the existing results for now. Best wishes, John

**Comment by ctSkennerton** [comment]
Can you try out the latest commit with your full input file. I've fixed it for the example that you sent me.

**Comment by johnomics** [comment]
Thank you very much for looking into this! The fix resolves some contigs but not others. We previously had 28 contigs causing errors, now we have 8.

I added a line to CRISPRFinder.java so I could see which contigs were causing the problem. Here are the original 28, 20 of which are now fine:
[original_contigs.fasta.gz](https://github.com/ctSkennerton/minced/files/2915087/original_contigs.fasta.gz)


And here are the remaining contigs that still throw errors:
[remaining_contigs.fasta.gz](https://github.com/ctSkennerton/minced/files/2915089/remaining_contigs.fasta.gz)

All of these remaining contigs are in the first set, so the fix hasn't generated new problems.

**Comment by ctSkennerton** [comment]
This time it should be fixed

**Comment by johnomics** [comment]
Excellent, that fixes the error and gives us another 35 arrays. Thank you very much! Best wishes, John

**Comment by johnomics** [comment]
(Tiny thing - v0.3.3 looks good except in CHANGES the version number isn't updated, 0.3.2 is there twice.)
