### ISSUE TITLE
Could you please allow for both gff output and minced file output?

### ISSUE THREAD

**Issue by oddaud** [ctSkennerton/minced#26]
Hi, 

thank you for an amazing tool! I use it often. I would like to be able to get both a minced standard output file as well as a gff (full) file. Right now, the -gffFull option prevents the creation of a standard minced output file. Do you think this would be an easy change to make? 

Thank you!
Audra

**Comment by ctSkennerton** [comment]
I think it is relatively easy, however I don't have a lot of time to work on personal projects right now. It might take me a couple of weeks to get to.

**Comment by ctSkennerton** [comment]
added in version 0.4.0
