### ISSUE TITLE
Name and length of sequence is off in the output

### ISSUE THREAD

**Issue by Russel88** [ctSkennerton/minced#30]
In the output (both gff and text) the name is missing if an array was found in the first sequence in a multi-sequence fasta. Furthermore, the sequence length for the first sequence is also off.

Is it only made to handle single-sequence fasta inputs?

Regards,
Jakob

**Comment by ctSkennerton** [comment]
I'm afraid I don't quite know what you mean by "an array was found in the
first sequence". The program should handle files with multiple records. Can
you send me an example input file so I can better see what you mean?

**Comment by Russel88** [comment]
I might have been a bit unclear. Try to run the following fasta through minced (I'm using version 0.4.0):
`wget ftp://ftp.ensemblgenomes.org/pub/bacteria/current/fasta/bacteria_93_collection/acetobacter_aceti_nbrc_14818/dna/Acetobacter_aceti_nbrc_14818.ASM96390v1.dna.toplevel.fa.gz`

`gzip -dc Acetobacter_aceti_nbrc_14818.ASM96390v1.dna.toplevel.fa.gz | minced /dev/stdin`

Here the name of the contig is missing in the output

**Comment by Russel88** [comment]
It appears to be the way I pipe the output into STDIN.
If I unzip first, then run minced on the unzipped fasta, everything looks good

**Comment by ctSkennerton** [comment]
Cool. I've never tried but I guess it doesn't work with piped input
