### ISSUE TITLE
identify the spacer sense strand

### ISSUE THREAD

**Issue by YiweiZhu** [ctSkennerton/minced#31]
Hi，
I am using minced to look for CRISPR array in P. aeruginosa which contains frequently the I-F subtype. In this subtype, the CRISPR array at the upstream of Cas genes transcripts in the opposite direction. However, the spacers of the upstream arrays listed in minced results are still in the same direction of the Cas genes. Is it possible for minced to identify the sense strand of spacers depending on the CRISPR/Cas types?
![图片](https://user-images.githubusercontent.com/41197115/82647802-4b69ec00-9c49-11ea-8bcc-f37fdc5ed77b.png)

**Comment by ctSkennerton** [comment]
No, minced doesn’t detect the direction of arrays.

**Comment by YiweiZhu** [comment]
Thank you all the same!
