### ISSUE TITLE
add repeat sequence to database

### ISSUE THREAD

**Issue by fabgenomics** [ctSkennerton/minced#33]
Hi, 
I was looking for a tool to do CRISPR typing in E. coli. Minced seems perfect for what I want to do but some of the repeat are not weel identified. For instance GAGTTCCCCGCCCCTGCGGTAGAACTCCC is one of my repeat that is not detected by minced.
Do you know how I can add repeat in the database minced use ?
Have a nice day,
Fabien

**Comment by ctSkennerton** [comment]
Minced doesn't have a database of sequences that it checks. It identifies repeats from the sequence it's run on.

**Comment by fabgenomics** [comment]
Ok thanks for your quick answer. Usually in E. coli the last repeat in CRISPR 2 is degenerated so it'll be missed.

**Comment by ctSkennerton** [comment]
Yeah, it's a known problem. Minced is an old program with a simple algorithm so many of the degenerate repeats towards the end will be missed.

**Comment by fabgenomics** [comment]
Even old it'll probably do the job for me. But If you know another one that I can try ?
