### ISSUE TITLE
understanding of the output file！

### ISSUE THREAD

**Issue by allen-zhan340** [ctSkennerton/minced#41]
I find two CRISPR in genome 'CP069814.1' (23 spacers in CRISPR 1 and 11 spacers in CRISPR 2), the picture shows below:

i wonder if i can align the 34 (23+11) spacers of genome 'CP069814.1' to some viral databases directly to infer the viral-host association.

it really confused us a lot. I don't know if the 34 sequence are all spacers of genome 'CP069814.1', because this is my first time using this software. 

i am sorry for troubling you so much. and thanks a lot for you answer!

![image](https://github.com/ctSkennerton/minced/assets/73383699/abcb94ae-052a-4e75-a75b-4a4524928932)

**Comment by ctSkennerton** [comment]
Hi @allen-zhan340, yes you can take the spacers and align them to a viral database. All of those spacers are from the sequence CP069814.1. On the left hand side is the "POSITION" which shows the location in the sequence.

**Comment by allen-zhan340** [comment]
Thanks so much for your response!  
and definitely appreciate for such convenient tools!
