### ISSUE TITLE
Need an option to get the version

### ISSUE THREAD

**Issue by tseemann** [ctSkennerton/minced#7]
Could you please add a ```--version``` or ```-version``` or ```-V``` option to print the current tool and version:

    % minced -version
    minced 0.1.6

This is important for putting into Galaxy etc.

**Comment by tseemann** [comment]
I notice it now seems to have a _hidden_ ```--version``` option, but it doesn't appear in the ```--help``` output?

**Comment by ctSkennerton** [comment]
fixed
